### ISSUE TITLE
Wire UI/Express to Simulator

### ISSUE THREAD

**Issue by ccday** [esrpg/server#19]
Hoo boy. This is a big one. We need to break down every request/response and basically figure out our external API, aka what Angular will hit via HTTP. Please comment below. I have an idea on some of  it but this is high priority and fairly complicated. So far:

- Starting/joining game session
- Selecting role + parameters (name, gender, etc)
- Receiving/posting actions
- Receiving updated game state

**Comment by gevorkgevoian** [comment]
For starting and joining game sessions: AngularJS will shoot a HTTP method to server on page load, and the server will create a new BusinessActor that it will keep in a temporary buffer/array until the current round reaches the end. The idea is to load new players in at the start of a fresh round, updating the view for both new and old players immediately after this is done.

**Comment by gevorkgevoian** [comment]
Largely implemented in Master. Missing a few small methods and overall unit and component testing.

**Comment by gevorkgevoian** [comment]
Implemented in integration. Still missing some functionality but covers the requirements of this issue. Will close once merged into Master.
